import json
import os
import sys

# All metadata files produced by data_preparation/*.py. The IPA sequence is always the
# 2nd pipe-separated field (index 1), regardless of whether the file has 2 columns
# (single-speaker) or 3 columns (multi-speaker with a trailing speaker_id).
METADATA_FILES = [
    "metadata.txt",
    "openslr_metadata.txt",
    "pathnirwana_metadata.txt",
]

# Punctuation the normalizer/G2P pipeline is known to pass through unchanged
# (see model_engine/normalizer.py pad_punctuation / remove_noise).
KNOWN_PUNCTUATION = set(".,?!'\"")


def _split_chars(char_set):
    """Splits a raw character set into (phoneme_characters, punctuations, has_space)."""
    has_space = " " in char_set
    char_set = char_set - {" "}
    punctuations = "".join(sorted(c for c in char_set if c in KNOWN_PUNCTUATION))
    phonemes = "".join(sorted(c for c in char_set if c not in KNOWN_PUNCTUATION))
    return phonemes, punctuations, has_space


def collect_characters(data_dir, filenames):
    combined_chars = set()
    per_file_chars = {}
    file_stats = {}

    for filename in filenames:
        path = os.path.join(data_dir, filename)
        if not os.path.exists(path):
            print(f"Skipping (not found): {path}")
            continue

        chars_in_file = set()
        line_count = 0
        with open(path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.rstrip("\n")
                if not line.strip():
                    continue
                parts = line.split("|")
                if len(parts) < 2:
                    continue
                chars_in_file.update(parts[1])
                line_count += 1

        combined_chars.update(chars_in_file)
        per_file_chars[filename] = chars_in_file
        file_stats[filename] = {"lines": line_count, "unique_chars": len(chars_in_file)}
        print(f"{filename}: {line_count} lines, {len(chars_in_file)} unique characters")

    return combined_chars, per_file_chars, file_stats


def build_vocab(target_file=None):
    """
    If target_file is given, only that single metadata file is inspected and the
    breakdown is printed (nothing is saved) — useful for manually checking one
    dataset at a time. If target_file is None, all available metadata files are
    combined and the shared ipa_vocab.json used by the VITS training configs is
    (re)written.
    """
    current_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(current_dir)
    data_dir = os.path.join(project_root, "data")

    filenames = [target_file] if target_file else METADATA_FILES

    combined_chars, per_file_chars, file_stats = collect_characters(data_dir, filenames)

    if not combined_chars:
        print("\nNo characters collected — make sure the metadata.txt file(s) exist in data/ "
              "and have been generated by the data_preparation scripts first.")
        return

    # ---- Per-dataset breakdown (so you can spot-check one dataset at a time) ----
    print("\n=== Per-dataset breakdown ===")
    for filename, chars in per_file_chars.items():
        phonemes, punctuations, has_space = _split_chars(chars)
        print(f"\n{filename}")
        print(f"  Phoneme characters ({len(phonemes)}): {phonemes}")
        print(f"  Punctuations ({len(punctuations)}): {punctuations}")
        print(f"  Space token present: {has_space}")

    if target_file:
        # Single-dataset inspection mode — don't touch the shared ipa_vocab.json.
        print("\n(Inspection mode: single dataset only — ipa_vocab.json was NOT modified.)")
        return

    # ---- Combined vocab (used for the actual VITS characters config) ----
    phoneme_chars, punctuations, has_space = _split_chars(combined_chars)

    vocab = {
        "phoneme_characters": phoneme_chars,
        "punctuations": punctuations,
        "has_space": has_space,
        "total_unique_characters": len(combined_chars),
        "source_files": file_stats,
    }

    out_path = os.path.join(current_dir, "ipa_vocab.json")
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(vocab, f, ensure_ascii=False, indent=2)

    print(f"\n=== Combined vocabulary saved to: {out_path} ===")
    print(f"Phoneme characters ({len(phoneme_chars)}): {phoneme_chars}")
    print(f"Punctuations ({len(punctuations)}): {punctuations}")
    print(f"Space token present: {has_space}")


if __name__ == "__main__":
    # Usage:
    #   python build_char_vocab.py                    -> combine all 3 datasets, save ipa_vocab.json
    #   python build_char_vocab.py metadata.txt        -> inspect only the custom dataset
    #   python build_char_vocab.py openslr_metadata.txt -> inspect only OpenSLR
    target = sys.argv[1] if len(sys.argv) > 1 else None
    build_vocab(target)
