import json
import os

# All metadata files produced by data_preparation/*.py. The IPA sequence is always the
# 2nd pipe-separated field (index 1), regardless of whether the file has 2 columns
# (single-speaker) or 3 columns (multi-speaker with a trailing speaker_id).
METADATA_FILES = [
    "metadata.txt",
    "openslr_metadata.txt",
    "pathnirwana_metadata.txt",
]

# Punctuation the normalizer/G2P pipeline is known to pass through unchanged
# (see model_engine/normalizer.py pad_punctuation / remove_noise).
KNOWN_PUNCTUATION = set(".,?!'\"")


def collect_characters(data_dir):
    all_chars = set()
    file_stats = {}

    for filename in METADATA_FILES:
        path = os.path.join(data_dir, filename)
        if not os.path.exists(path):
            print(f"Skipping (not found): {path}")
            continue

        chars_in_file = set()
        line_count = 0
        with open(path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.rstrip("\n")
                if not line.strip():
                    continue
                parts = line.split("|")
                if len(parts) < 2:
                    continue
                ipa_seq = parts[1]
                chars_in_file.update(ipa_seq)
                line_count += 1

        all_chars.update(chars_in_file)
        file_stats[filename] = {"lines": line_count, "unique_chars": len(chars_in_file)}
        print(f"{filename}: {line_count} lines, {len(chars_in_file)} unique characters")

    return all_chars, file_stats


def build_vocab():
    current_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(current_dir)
    data_dir = os.path.join(project_root, "data")

    all_chars, file_stats = collect_characters(data_dir)

    if not all_chars:
        print("\nNo characters collected — make sure the metadata.txt files exist in data/ "
              "and have been generated by the data_preparation scripts first.")
        return

    # Space separates IPA tokens (words/punctuation) within a sequence, so it must be
    # part of the vocabulary too, but Coqui's CharactersConfig takes it as a distinct
    # "blank"/word-boundary symbol rather than a regular character, so we split it out.
    space_present = " " in all_chars
    all_chars.discard(" ")

    punctuations = sorted(c for c in all_chars if c in KNOWN_PUNCTUATION)
    phoneme_chars = sorted(c for c in all_chars if c not in KNOWN_PUNCTUATION)

    vocab = {
        "phoneme_characters": "".join(phoneme_chars),
        "punctuations": "".join(punctuations),
        "has_space": space_present,
        "total_unique_characters": len(all_chars) + (1 if space_present else 0),
        "source_files": file_stats,
    }

    out_path = os.path.join(current_dir, "ipa_vocab.json")
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(vocab, f, ensure_ascii=False, indent=2)

    print(f"\nSaved character vocabulary to: {out_path}")
    print(f"Phoneme characters ({len(phoneme_chars)}): {vocab['phoneme_characters']}")
    print(f"Punctuations ({len(punctuations)}): {vocab['punctuations']}")
    print(f"Space token present: {space_present}")


if __name__ == "__main__":
    build_vocab()
